sensor:
- platform: toptronic
  name: Modulazione ventilazione normale
  function_group: 50
  function_number: 0
  datapoint: 40651
  id: HV_50_0_40651
  type: U8
  unit_of_measurement: '%'
- platform: toptronic
  name: Modulazione ventilazione risparmio
  function_group: 50
  function_number: 0
  datapoint: 40686
  id: HV_50_0_40686
  type: U8
  unit_of_measurement: '%'
- platform: toptronic
  name: Modulazione ventilazione
  function_group: 50
  function_number: 0
  datapoint: 38606
  id: HV_50_0_38606
  type: U8
  unit_of_measurement: '%'
- platform: toptronic
  name: "Valore nominale umidit\xE0"
  function_group: 50
  function_number: 0
  datapoint: 40687
  id: HV_50_0_40687
  type: U8
  unit_of_measurement: '%'
- platform: toptronic
  name: "Umidit\xE0 aria ripresa"
  function_group: 50
  function_number: 0
  datapoint: 37600
  id: HV_50_0_37600
  type: U8
  unit_of_measurement: '%'
- platform: toptronic
  name: VOC aria ripresa
  function_group: 50
  function_number: 0
  datapoint: 37608
  id: HV_50_0_37608
  type: U8
  unit_of_measurement: '%'
- platform: toptronic
  name: VOC aria esterna
  function_group: 50
  function_number: 0
  datapoint: 37611
  id: HV_50_0_37611
  type: U8
  unit_of_measurement: '%'
- platform: toptronic
  name: Temperatura aria esterna
  function_group: 50
  function_number: 0
  datapoint: 0
  id: HV_50_0_0
  type: S16
  unit_of_measurement: "\xB0C"
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
- platform: toptronic
  name: Temperatura aria ripresa
  function_group: 50
  function_number: 0
  datapoint: 37602
  id: HV_50_0_37602
  type: S16
  unit_of_measurement: "\xB0C"
  accuracy_decimals: 1
  filters:
  - multiply: 0.1
- platform: toptronic
  name: Ventilatore aria espulsa nominale
  function_group: 50
  function_number: 0
  datapoint: 38600
  id: HV_50_0_38600
  type: U8
  unit_of_measurement: '%'
text_sensor:
- platform: toptronic
  name: Selezione modo funzion.to ventilazione
  function_group: 50
  function_number: 0
  datapoint: 40650
  id: HV_50_0_40650
  options:
  - Stand-by
  - Settimana 1
  - Settimana 2
  - Modo costante, valore nominale 40651
  - Modo risparmio, valore nominale DAP40686
  values:
  - 0
  - 1
  - 2
  - 4
  - 5
- platform: toptronic
  name: Stato regolazione ventilazione
  function_group: 50
  function_number: 0
  datapoint: 39652
  id: HV_50_0_39652
  options:
  - Apparecchio off, per es. modo Stand-by
  - Modo ventilazione normale
  - Modo VOC attivo
  - "Modo umidit\xE0 attivo"
  - Protezione antigelo attiva
  - CoolVent attivo
  - Stato errore
  - "Umidit\xE0 estiva"
  - Stop spegnimento valore nominale
  values:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
