number:
- platform: toptronic
  name: Normal room temp. heating oper.
  function_group: 1
  function_number: 0
  datapoint: 3051
  id: WEZ_1_0_3051_set
  type: S16
  unit_of_measurement: "\xB0C"
  min_value: 100
  max_value: 300
  step: 5
  decimal: 1
- platform: toptronic
  name: Conservation room temp. heating oper.
  function_group: 1
  function_number: 0
  datapoint: 3053
  id: WEZ_1_0_3053_set
  type: S16
  unit_of_measurement: "\xB0C"
  min_value: 50
  max_value: 200
  step: 5
  decimal: 1
- platform: toptronic
  name: Normal room temp. heating oper.
  function_group: 1
  function_number: 1
  datapoint: 3051
  id: WEZ_1_1_3051_set
  type: S16
  unit_of_measurement: "\xB0C"
  min_value: 100
  max_value: 300
  step: 5
  decimal: 1
- platform: toptronic
  name: Conservation room temp. heating oper.
  function_group: 1
  function_number: 1
  datapoint: 3053
  id: WEZ_1_1_3053_set
  type: S16
  unit_of_measurement: "\xB0C"
  min_value: 50
  max_value: 200
  step: 5
  decimal: 1
- platform: toptronic
  name: Normal room temp. heating oper.
  function_group: 1
  function_number: 2
  datapoint: 3051
  id: WEZ_1_2_3051_set
  type: S16
  unit_of_measurement: "\xB0C"
  min_value: 100
  max_value: 300
  step: 5
  decimal: 1
- platform: toptronic
  name: Conservation room temp. heating oper.
  function_group: 1
  function_number: 2
  datapoint: 3053
  id: WEZ_1_2_3053_set
  type: S16
  unit_of_measurement: "\xB0C"
  min_value: 50
  max_value: 200
  step: 5
  decimal: 1
select:
- platform: toptronic
  name: Heating operation choice
  function_group: 1
  function_number: 0
  datapoint: 3050
  id: WEZ_1_0_3050_set
  options:
  - Standby
  - week 1
  - week 2
  - constant
  - Eco mode
  - Manual operating mode heating
  - Manual operating mode cooling
  values:
  - 0
  - 1
  - 2
  - 4
  - 5
  - 7
  - 8
- platform: toptronic
  name: Heating operation choice
  function_group: 1
  function_number: 1
  datapoint: 3050
  id: WEZ_1_1_3050_set
  options:
  - Standby
  - week 1
  - week 2
  - constant
  - Eco mode
  - Manual operating mode heating
  - Manual operating mode cooling
  values:
  - 0
  - 1
  - 2
  - 4
  - 5
  - 7
  - 8
- platform: toptronic
  name: Heating operation choice
  function_group: 1
  function_number: 2
  datapoint: 3050
  id: WEZ_1_2_3050_set
  options:
  - Standby
  - week 1
  - week 2
  - constant
  - Eco mode
  - Manual operating mode heating
  - Manual operating mode cooling
  values:
  - 0
  - 1
  - 2
  - 4
  - 5
  - 7
  - 8
