number:
- platform: toptronic
  name: Normal-Raumtemperatur Heizbetrieb
  function_group: 1
  function_number: 0
  datapoint: 3051
  id: WEZ_1_0_3051_set
  type: S16
  unit_of_measurement: "\xB0C"
  min_value: 100
  max_value: 300
  step: 5
  decimal: 1
- platform: toptronic
  name: Spar-Raumtemperatur Heizbetrieb
  function_group: 1
  function_number: 0
  datapoint: 3053
  id: WEZ_1_0_3053_set
  type: S16
  unit_of_measurement: "\xB0C"
  min_value: 50
  max_value: 200
  step: 5
  decimal: 1
- platform: toptronic
  name: Normal-Raumtemperatur Heizbetrieb
  function_group: 1
  function_number: 1
  datapoint: 3051
  id: WEZ_1_1_3051_set
  type: S16
  unit_of_measurement: "\xB0C"
  min_value: 100
  max_value: 300
  step: 5
  decimal: 1
- platform: toptronic
  name: Spar-Raumtemperatur Heizbetrieb
  function_group: 1
  function_number: 1
  datapoint: 3053
  id: WEZ_1_1_3053_set
  type: S16
  unit_of_measurement: "\xB0C"
  min_value: 50
  max_value: 200
  step: 5
  decimal: 1
- platform: toptronic
  name: Normal-Raumtemperatur Heizbetrieb
  function_group: 1
  function_number: 2
  datapoint: 3051
  id: WEZ_1_2_3051_set
  type: S16
  unit_of_measurement: "\xB0C"
  min_value: 100
  max_value: 300
  step: 5
  decimal: 1
- platform: toptronic
  name: Spar-Raumtemperatur Heizbetrieb
  function_group: 1
  function_number: 2
  datapoint: 3053
  id: WEZ_1_2_3053_set
  type: S16
  unit_of_measurement: "\xB0C"
  min_value: 50
  max_value: 200
  step: 5
  decimal: 1
select:
- platform: toptronic
  name: Betriebswahl Heizung
  function_group: 1
  function_number: 0
  datapoint: 3050
  id: WEZ_1_0_3050_set
  options:
  - Standby
  - Woche 1
  - Woche 2
  - Konstant
  - Sparbetrieb
  - Handbetrieb Heizen
  - "Handbetrieb K\xFChlen"
  values:
  - 0
  - 1
  - 2
  - 4
  - 5
  - 7
  - 8
- platform: toptronic
  name: Betriebswahl Heizung
  function_group: 1
  function_number: 1
  datapoint: 3050
  id: WEZ_1_1_3050_set
  options:
  - Standby
  - Woche 1
  - Woche 2
  - Konstant
  - Sparbetrieb
  - Handbetrieb Heizen
  - "Handbetrieb K\xFChlen"
  values:
  - 0
  - 1
  - 2
  - 4
  - 5
  - 7
  - 8
- platform: toptronic
  name: Betriebswahl Heizung
  function_group: 1
  function_number: 2
  datapoint: 3050
  id: WEZ_1_2_3050_set
  options:
  - Standby
  - Woche 1
  - Woche 2
  - Konstant
  - Sparbetrieb
  - Handbetrieb Heizen
  - "Handbetrieb K\xFChlen"
  values:
  - 0
  - 1
  - 2
  - 4
  - 5
  - 7
  - 8
