substitutions:
    HV_0_0_29042: Active error 1_appearance_time
    HV_0_0_29043: Active error 2_appearance_time
    HV_0_0_29044: Active error 3_appearance_time
    HV_0_0_29045: Active error 4_appearance_time
    HV_0_0_29046: Active error 5_appearance_time
    HV_50_0_0: Outside air temp.
    HV_50_0_37600: Humidity extract air
    HV_50_0_37602: Extract air temp.
    HV_50_0_37608: VOC extract air
    HV_50_0_37611: VOC outdoor air
    HV_50_0_38600: Fan exhaust air set
    HV_50_0_38606: Ventilation modulation
    HV_50_0_39600: Air quality control
    HV_50_0_39652: Status vent regulation
    HV_50_0_40650: Op. choice ventilation
    HV_50_0_40651: Constant ventilation modulation
    HV_50_0_40686: Eco ventilation modulation
    HV_50_0_40687: Humidity set value
    
    HV_83_1_0: Photosensor
    HV_50_0_2010: Party mode timer [h]
    
    
    ##### values
    
    HV_50_0_39652_val_1: Constant ventilation mode
    HV_50_0_39652_val_2: VOC mode active
    HV_50_0_39652_val_3: Humidity mode active
    HV_50_0_39652_val_4: Frost protection active
    HV_50_0_39652_val_5: CoolVent active
    HV_50_0_39652_val_6: Fault status
    HV_50_0_39652_val_7: Summer humidity
    HV_50_0_39652_val_8: Switch-off stop
    
    
    HV_50_0_40650_val_1 : Standby
    HV_50_0_40650_val_2 : Week 1
    HV_50_0_40650_val_3 : Week 2
    HV_50_0_40650_val_4 : Constant
    HV_50_0_40650_val_5 : Eco
    
