esphome:
  name: $name
  on_boot:
    priority: 200  
    then:
      - wait_until:  
          condition:
            wifi.connected: 
          timeout: 15s
  
esp32:
  board: nodemcu-32s
  framework:
    type: arduino #esp-idf  not ready missing json and async_tcp
    version: recommended #latest
#    sdkconfig_options:
#      CONFIG_COMPILER_OPTIMIZATION_SIZE: y

preferences:
  flash_write_interval: 60min
  
# Enable logging
logger:
  level: DEBUG #NONE# ERROR #INFO #DEBUG  #VERBOSE
  #baud_rate: 0 #to disable logging via UART
  logs:
    text_sensor : ERROR
    homeassistant.sensor: ERROR
    canbus: INFO # setting log level for canbus lower than INFO may crash  : esphome/issues#4051
    #uptime: NONE
    uptime.sensor: NONE
    #wifi_signal : NONE
    wifi_signal.sensor: NONE
    esp32.preferences : NONE
    internal_temperature : NONE


# Enable Home Assistant API
api:
  reboot_timeout: 30min
      

ota:

