canbus:
  - platform: esp32_can
    tx_pin: GPIO5
    rx_pin: GPIO4
    can_id: 8
    bit_rate: 50kbps
    on_frame:
    - can_id: 0x1f
      can_id_mask: 0x0000001f
      use_extended_id: true
      then:
      - lambda: |-
         if(x.size() > 6) {
            uint32_t myInt1 = x[5] + (x[4] << 8);
            switch(myInt1) {
                case 38606:
                    id(HV_50_0_38606).publish_state((uint8_t)x[6]);
                    break;
                case 40687:
                    id(HV_50_0_40687).publish_state((uint8_t)x[6]);
                    break;
                case 37600:
                    id(HV_50_0_37600).publish_state((uint8_t)x[6]);
                    break;
            }
            if(x.size() > 7) {
                int temp = (int16_t)(x[6] << 8) + x[7];
                switch(myInt1) {
                    case 0:
                        id(HV_50_0_0).publish_state(temp);
                        break;
                    case 37602:
                        id(HV_50_0_37602).publish_state(temp);
                        break;
                    }
            }
         }