
    # """Operations in CAN-Message"""
    # RESPONSE = 0x42
    # GET_REQUEST = 0x40
    # SET_REQUEST = 0x46

script:

########### Canbus Sensors #########

  - id: HV_50_0_37600_request #datapoint 37600 : Humidity extract air
    # the hard part was to find the correct can ID with candump. (sending to 0x1F do not works)
    # Candump = can0  1FE04208   [6]  01 40 32 00 92 E0
    # 37600 to hex = 92E0
    #data : message_len = 0x01, operation = 0x40, function_group = 50 (0x32), function_number = 0 (0x00), datapoint = 37600 (92E0) 
    then:
        - canbus.send:
            canbus_id: cbus
            can_id: ${hoval_toptronic_can_Addr} #0x1FE04208
            data: [0x01, 0x40, 0x32, 0x00, 0x92, 0xE0]
            use_extended_id: true
            
  - id: HV_50_0_37602_request #datapoint 37602: Extract air temp.
    then:
        - canbus.send:
            canbus_id: cbus
            can_id: ${hoval_toptronic_can_Addr} #0x1FE04208
            data: [0x01, 0x40, 0x32, 0x00, 0x92, 0xE2]
            use_extended_id: true
            
  - id: HV_50_0_0_request #datapoint 0 : Outside air temp.
    then:
        - canbus.send:
            canbus_id: cbus
            can_id: ${hoval_toptronic_can_Addr} #0x1FE04208
            data: [0x01, 0x40, 0x32, 0x00, 0x00, 0x00]
            use_extended_id: true

  - id: HV_50_0_38606_request #datapoint 38606 : Ventilation modulation
    then:
        - canbus.send:
            canbus_id: cbus
            can_id: ${hoval_toptronic_can_Addr} #0x1FE04208
            data: [0x01, 0x40, 0x32, 0x00, 0x96, 0xCE]
            use_extended_id: true

  - id: HV_50_0_40650_request #datapoint 40650 : Op. choice ventilation
    then:
        - canbus.send:
            canbus_id: cbus
            can_id: ${hoval_toptronic_can_Addr} #0x1FE04208
            data: [0x01, 0x40, 0x32, 0x00, 0x9E, 0xCA]
            use_extended_id: true            
            
  - id: HV_50_0_40651_request #datapoint 40651 : Normal ventilation modulation
    then:
        - canbus.send:
            canbus_id: cbus
            can_id: ${hoval_toptronic_can_Addr} #0x1FE04208
            data: [0x01, 0x40, 0x32, 0x00, 0x9E, 0xCB]
            use_extended_id: true    
            
  - id: HV_50_0_40686_request #datapoint 40686 : Eco ventilation modulation 
    then:
        - canbus.send:
            canbus_id: cbus
            can_id: ${hoval_toptronic_can_Addr} #0x1FE04208
            data: [0x01, 0x40, 0x32, 0x00, 0x9E, 0xEE]
            use_extended_id: true    
            
  # - id: HV_50_0_2010_request #datapoint 2010: undocumented HV_50_0_2010 Party mode timer [h]
    # then:
        # - canbus.send:
            # canbus_id: cbus
            # can_id: ${hoval_toptronic_can_Addr} 
            # data: [0x01, 0x40, 0x32, 0x00, 0x07, 0xDA]
            # use_extended_id: true   
            
            
  # - id: HV_83_1_0_request #datapoint 0: undocumented photosensor in fct group 83 
    # then:
        # - canbus.send:
            # canbus_id: cbus
            # can_id: ${hoval_toptronic_can_Addr} #0x1FE04208
            # data: [0x01, 0x40, 0x53, 0x01, 0x00, 0x00]
            # use_extended_id: true   

 
            

  # - id: HV_50_0_40650_set_constant #cansend can0 1FE04208#014632009ECA04
    # then:
        # - canbus.send:
            # canbus_id: cbus
            # can_id: ${hoval_toptronic_can_Addr} #0x1FE04208;
            # data: [0x01, 0x46, 0x32, 0x00, 0x9E, 0xCA, 0x04] #can0  1FE04208   [7]  01 46 32 00 9E CA 04
            # use_extended_id: true   




########### Canbus on boot requests #########

  - id: canbus_on_boot_requests # 1 time request is enough to get values until hoval reboot
    then:
        - delay: 2s
        - script.execute: HV_50_0_37600_request
        - delay: 2s
        - script.execute: HV_50_0_37602_request
        - delay: 2s
        - script.execute: HV_50_0_0_request
        - delay: 2s
        - script.execute: HV_50_0_38606_request
        - delay: 2s
        - script.execute: HV_50_0_40650_request
        - delay: 2s
        - script.execute: HV_50_0_40651_request
        - delay: 2s
        - script.execute: HV_50_0_40686_request
        #- delay: 2s
        #- script.execute: HV_83_1_0_request

      