canbus:
  - platform: esp32_can
    tx_pin: GPIO5
    rx_pin: GPIO4
    can_id: 8
    bit_rate: 50kbps
    on_frame:
    - can_id: 0x1f
      can_id_mask: 0x0000001f
      use_extended_id: true
      then:
      - lambda: |-
         if(x.size() > 6) {
            uint32_t myInt1 = x[5] + (x[4] << 8);
            switch(myInt1) {

                    case 40651:
                        id(HV_50_0_40651).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_50_0_40651} is %f", (uint8_t)x[6]);
                        break;
                
                    case 40686:
                        id(HV_50_0_40686).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_50_0_40686} is %f", (uint8_t)x[6]);
                        break;
                
                    case 38606:
                        id(HV_50_0_38606).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_50_0_38606} is %f", (uint8_t)x[6]);
                        break;
                
                    case 40687:
                        id(HV_50_0_40687).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_50_0_40687} is %f", (uint8_t)x[6]);
                        break;
                
                    case 37600:
                        id(HV_50_0_37600).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_50_0_37600} is %f", (uint8_t)x[6]);
                        break;
                
                    case 37608:
                        id(HV_50_0_37608).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_50_0_37608} is %f", (uint8_t)x[6]);
                        break;
                
                    case 37611:
                        id(HV_50_0_37611).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_50_0_37611} is %f", (uint8_t)x[6]);
                        break;
                
                    case 39652:
                        id(HV_50_0_39652).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_50_0_39652} is %f", (uint8_t)x[6]);
                        break;
                
                    case 38600:
                        id(HV_50_0_38600).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_50_0_38600} is %f", (uint8_t)x[6]);
                        break;
                
                    case 29042:
                        id(HV_0_0_29042).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_0_0_29042} is %f", (uint8_t)x[6]);
                        break;
                
                    case 29043:
                        id(HV_0_0_29043).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_0_0_29043} is %f", (uint8_t)x[6]);
                        break;
                
                    case 29044:
                        id(HV_0_0_29044).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_0_0_29044} is %f", (uint8_t)x[6]);
                        break;
                
                    case 29045:
                        id(HV_0_0_29045).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_0_0_29045} is %f", (uint8_t)x[6]);
                        break;
                
                    case 29046:
                        id(HV_0_0_29046).publish_state((uint8_t)x[6]);
                        ESP_LOGD("main", "${HV_0_0_29046} is %f", (uint8_t)x[6]);
                        break;
                
            }
            if(x.size() > 7) {
                int temp = (int16_t)(x[6] << 8) + x[7];
                switch(myInt1) {
                    case 0:
                        id(HV_50_0_0).publish_state((int16_t)(x[6] << 8) + x[7]);
                        ESP_LOGD("main", "${HV_50_0_0} is %f", (int16_t)(x[6] << 8) + x[7]);
                        break;


                    case 37602:
                        id(HV_50_0_37602).publish_state((int16_t)(x[6] << 8) + x[7]);
                        ESP_LOGD("main", "${HV_50_0_37602} is %f", (int16_t)(x[6] << 8) + x[7]);
                        break;
                    }
            }
         }
