# for flashing : press boot button for 2-3 seconds before the serial connection initialize
# After OTA update, the EN (reset) button must be pressed to run firmware
# do not use gpio12 (MTDI)

substitutions:
  name: canbus
  friendly_name: "CanBus Controller"
  TZ: "Europe/Zurich" #timezone
  
  ### canbus 
  can_tx_pin: "GPIO22" #GPIO5
  can_rx_pin: "GPIO21" #GPIO4
  can_can_id: "8"
  ## you can get the next values by activating the code under the section "Find can_id " in canbus.yaml
  hoval_homevent_canID: "0x1FD047FF" # to get sensors values | 0x1f ## works, but must process all frames and cpu is heating
  hoval_toptronic_canID: "0x1FE04208" #to send sensors requests
  
  

packages:
  wifi: !include wifi.yaml
  board: !include board.yaml
  time: !include time.yaml
  ## translations / substitutions
  substitutions_EN: !include substitutions_EN.yaml
  #substitutions_DE: !include substitutions_DE.yaml
  #substitutions_FR: !include substitutions_FR.yaml
  #substitutions_IT: !include substitutions_IT.yaml
  canbus: !include canbus.yaml
  canbus_scripts: !include canbus_scripts.yaml
  sensor_canbus: !include sensor_canbus.yaml
  sensor_others: !include sensor_others.yaml
  switch: !include switch.yaml
  number: !include inputs_number.yaml
  select: !include inputs_select.yaml
  
web_server:
  port: 80
  #log: false

