    # """Operations in CAN-Message"""
    # RESPONSE = 0x42
    # GET_REQUEST = 0x40
    # SET_REQUEST = 0x46

   
######### select 
select:
###select: # 40650 : Op. choice ventilation (e.g. week 1 / 2, constant, standby)
  - platform: template
    name: "${HV_50_0_40650} update"
    id: HV_50_0_40650_set
    optimistic: true
    initial_option: "--"
    options:
      - "--"
      - "${HV_50_0_40650_val_1}" #0 Standby
      - "${HV_50_0_40650_val_2}" #1 Week 1
      - "${HV_50_0_40650_val_3}" #2 Week 2
      - "${HV_50_0_40650_val_4}" #4 Constant
      - "${HV_50_0_40650_val_5}" #5 Eco
    on_value:
      then:
        - lambda: |-
            uint8_t action = 99;
            if ( x == "${HV_50_0_40650_val_1}") {
              action = 0;
              // there is no update of sensors in standby mode ...
              id(HV_50_0_40650).publish_state(0); //Op. choice ventilation
              id(HV_50_0_39652).publish_state(0); //Status vent regulation
              id(HV_50_0_38606).publish_state(0); //Ventilation modulation
            }else if ( x == "${HV_50_0_40650_val_2}") {
              action = 1;
            }else if ( x == "${HV_50_0_40650_val_3}") {
              action = 2;
            }else if ( x == "${HV_50_0_40650_val_4}") {
              action = 4;
            }else if ( x == "${HV_50_0_40650_val_5}") {
              action = 5;
            }else if ( x == "--") {
              return;
            }
            uint32_t can_id = ${hoval_toptronic_can_Addr}; //0x1FE04208;
            bool use_extended_id = 1;
            std::vector< uint8_t > data{0x01, 0x46, 0x32, 0x00, 0x9E, 0xCA, action}; //can0  1FE04208   [7]  01 46 32 00 9E CA 04
            id(cbus)->send_data(can_id, use_extended_id, data);  
            
        # - delay: 2s
        # - script.execute: HV_50_0_40650_request
  

### debug sensors

  # - platform: template
    # name: "Debug sensors"
    # id: canbus_debug_sensors
    # optimistic: true
    # options:
      # - "none"
      # - "GET-Humidity-extract-air"
      # - "GET-Extract-air-temp"
      # - "GET-Outside-air-temp"
      # - "GET-Ventilation-modulation"
      # - "GET-Op-choice-ventilation"
      # - "GET-Normal-ventilation-modulation"
      # - "GET-Eco-ventilation-modulation"
      # - "GET-Photosensor"
      # - "GET-Party-mode-timer"
    # on_value:
      # then:
        # - lambda: |-
            # if ( x == "GET-Humidity-extract-air") {
                # id(HV_50_0_37600_request).execute();
            # }else if ( x == "GET-Extract-air-temp") {
                # id(HV_50_0_37602_request).execute();
            # }else if ( x == "GET-Outside-air-temp") {
                # id(HV_50_0_0_request).execute();
            # }else if ( x == "GET-Ventilation-modulation") {
                # id(HV_50_0_38606_request).execute();
            # }else if ( x == "GET-Op-choice-ventilation") {
                # id(HV_50_0_40650_request).execute();
            # }else if ( x == "GET-Normal-ventilation-modulation") {
                # id(HV_50_0_40651_request).execute();
            # }else if ( x == "GET-Eco-ventilation-modulation") {
                # id(HV_50_0_40686_request).execute();
            # }else if ( x == "GET-Photosensor") {
                # id(HV_83_1_0_request).execute();
            # }else if ( x == "GET-Party-mode-timer") {
                # id(HV_50_0_2010_request).execute();
            # }
 




    
# Get users passwords (need cbus_psw to be activated in canbus.yaml)

##select: 
  # - platform: template
    # name: "Get users passwords"
    # id: canbus_get_psw
    # optimistic: true
    # initial_option: "None"
    # options:
      # - "None"
      # - "GET-user-password-1"
      # - "GET-user-password-2"
      # - "GET-user-password-3"
      # - "GET-user-password-4"
      # - "GET-user-password-5"
      # - "GET-user-password-6"
      # - "GET-user-password-7"
    # on_value:
      # then: #data : message_len = 0x01, operation = 0x40, function_group = 89 (0x59), function_number = 1 (0x01), datapoint = 1 (0x01) to 7
        # - lambda: |-
            # uint8_t user = 0xFF;
            # if ( x == "GET-user-password-1") {
              # user = 0x01;
            # }else if ( x == "GET-user-password-2") {
              # user = 0x02;
            # }else if ( x == "GET-user-password-3") {
              # user = 0x03;
            # }else if ( x == "GET-user-password-4") {
              # user = 0x04;
            # }else if ( x == "GET-user-password-5") {
              # user = 0x05;
            # }else if ( x == "GET-user-password-6") {
              # user = 0x06;
            # }else if ( x == "GET-user-password-7") {
              # user = 0x07;
            # }
            # uint32_t can_id = ${hoval_toptronic_can_Addr}; //0x1FE04208;
            # bool use_extended_id = 1;
            # std::vector< uint8_t > data{0x01, 0x40, 0x59, 0x01, user};
            # id(cbus)->send_data(can_id, use_extended_id, data);   


