
number:
   
  - platform: template
    name: ${HV_50_0_40687} #Humidity set value
    optimistic: true
    min_value: 30
    max_value: 65
    step: 1
    restore_value: false
    unit_of_measurement: '%'
    icon: mdi:water_percent
    device_class: humidity
    id: HV_50_0_40687_set

