sensor:
    #Op. choice ventilation
    - platform: template
      id: HV_50_0_40650
      name: ${HV_50_0_40650}
      accuracy_decimals: 0
      
      #Normal ventilation modulation
    - platform: template
      id: HV_50_0_40651
      name: ${HV_50_0_40651}
      accuracy_decimals: 0
      unit_of_measurement: '%'
      
     #Eco ventilation modulation 
    - platform: template
      id: HV_50_0_40686
      name: ${HV_50_0_40686}
      accuracy_decimals: 0
      unit_of_measurement: '%'
      
      #Ventilation modulation
    - platform: template
      id: HV_50_0_38606
      name: ${HV_50_0_38606}
      accuracy_decimals: 0
      unit_of_measurement: '%'
      
      #Humidity set value
    - platform: template
      id: HV_50_0_40687 
      name: ${HV_50_0_40687}
      accuracy_decimals: 0
      unit_of_measurement: '%'
      icon: mdi:water-percent
      device_class: humidity
      state_class: measurement
      
      #Humidity extract air
    - platform: template
      id: HV_50_0_37600
      name: ${HV_50_0_37600}
      accuracy_decimals: 0
      unit_of_measurement: '%'
      icon: mdi:water-percent
      device_class: humidity
      state_class: measurement
      
      #VOC extract air
    # - platform: template
      # id: HV_50_0_37608
      # name: ${HV_50_0_37608}
      # accuracy_decimals: 0
      # unit_of_measurement: '%'
      
      #VOC outdoor air
    # - platform: template
      # id: HV_50_0_37611
      # name: ${HV_50_0_37611}
      # accuracy_decimals: 0
      # unit_of_measurement: '%'
      
      #Air quality control
    # - platform: template
      # id: HV_50_0_39600
      # name: ${HV_50_0_39600}
      # accuracy_decimals: 0
      
      #Status vent. regulation
    - platform: template
      id: HV_50_0_39652
      name: ${HV_50_0_39652}
      accuracy_decimals: 0
      on_raw_value:
          then:
            - text_sensor.template.publish:
                id: HV_50_0_39652_text
                state: !lambda |-
                  int val = (id(HV_50_0_39652).raw_state);
                  return val == 0 ? "Off": (val == 1 ? "${HV_50_0_39652_val_1}": (val == 2 ? "${HV_50_0_39652_val_2}": (val == 3 ? "${HV_50_0_39652_val_3}": (val == 4 ? "${HV_50_0_39652_val_4}": (val == 5 ? "${HV_50_0_39652_val_5}": (val == 6 ? "${HV_50_0_39652_val_6}": (val == 7 ? "${HV_50_0_39652_val_7}": (val == 8 ? "${HV_50_0_39652_val_8}": "Undefined"))))))));
      
      #Outside air temp.
    - platform: template
      id: HV_50_0_0
      name: ${HV_50_0_0}
      accuracy_decimals: 1
      unit_of_measurement: "\xB0C"
      filters:
      - multiply: 0.1
      icon: mdi:temperature-celsius
      device_class: temperature
      state_class: measurement
      
      #Extract air temp.
    - platform: template
      id: HV_50_0_37602
      name: ${HV_50_0_37602}
      accuracy_decimals: 1
      unit_of_measurement: "\xB0C"
      filters:
      - multiply: 0.1
      icon: mdi:temperature-celsius
      device_class: temperature
      state_class: measurement
      
      #Fan exhaust air set
    # - platform: template
      # id: HV_50_0_38600
      # name: ${HV_50_0_38600}
      # accuracy_decimals: 0
      # unit_of_measurement: '%'
      
      # Active error
    # - platform: template
      # id: HV_0_0_29042
      # name: ${HV_0_0_29042}
      # accuracy_decimals: 0
    # - platform: template
      # id: HV_0_0_29043
      # name: ${HV_0_0_29043}
      # accuracy_decimals: 0
    # - platform: template
      # id: HV_0_0_29044
      # name: ${HV_0_0_29044}
      # accuracy_decimals: 0
    # - platform: template
      # id: HV_0_0_29045
      # name: ${HV_0_0_29045}
      # accuracy_decimals: 0
    # - platform: template
      # id: HV_0_0_29046
      # name: ${HV_0_0_29046}
      # accuracy_decimals: 0

    # - platform: template
      # id: HV_50_0_2010 #Party mode timer [h]
      # name: ${HV_50_0_2010}
      # accuracy_decimals: 0
      
    # - platform: template
      # id: HV_83_1_0
      # name: ${HV_83_1_0} # Photosensor
      # accuracy_decimals: 0


text_sensor:  
      #Status vent. regulation (text)
    - platform: template
      id: HV_50_0_39652_text
      name: ${HV_50_0_39652} text
