substitutions:
    HV_0_0_29042: Erreur active 1_appearance_time
    HV_0_0_29043: Erreur active 2_appearance_time
    HV_0_0_29044: Erreur active 3_appearance_time
    HV_0_0_29045: Erreur active 4_appearance_time
    HV_0_0_29046: Erreur active 5_appearance_time
    HV_50_0_0: "Temp\xE9rature de l'air ext\xE9rieur"
    HV_50_0_37600: "Humidit\xE9 de l'air extrait"
    HV_50_0_37602: "Temp\xE9rature de l'air extrait"
    HV_50_0_37608: VOC air extrait
    HV_50_0_37611: "VOC air ext\xE9rieur"
    HV_50_0_38600: "Ventilateur air \xE9vacu\xE9 val. de consigne"
    HV_50_0_38606: Modulation de la ventilation
    HV_50_0_39600: "Qualit\xE9 de l'air, r\xE9gulation"
    HV_50_0_39652: "\xC9tat r\xE9gulation de la ventilation"
    HV_50_0_40650: "S\xE9lection de fonctionnement ventilation"
    HV_50_0_40651: Modulation de la ventilation normale
    HV_50_0_40686: "Modulation de la ventilation \xE9conomique"
    HV_50_0_40687: "Valeur de consigne humidit\xE9"
    
    
    ##### values
    
    HV_50_0_39652_val_1: "Mode ventilation normale"
    HV_50_0_39652_val_2: "Mode VOC activ\xE9"
    HV_50_0_39652_val_3: "Mode humidit\xE9 activ\xE9"
    HV_50_0_39652_val_4: "Protection antigel activ\xE9e"
    HV_50_0_39652_val_5: "CoolVent activ\xE9"
    HV_50_0_39652_val_6: "Etat d’erreur"
    HV_50_0_39652_val_7: "Humidit\xE9 d\x27\xE9t\xE9"
    HV_50_0_39652_val_8: "Arr\xEAt coupure valeur de consigne"