substitutions:
    HV_0_0_29042: Errore attivo 1_appearance_time
    HV_0_0_29043: Errore attivo 2_appearance_time
    HV_0_0_29044: Errore attivo 3_appearance_time
    HV_0_0_29045: Errore attivo 4_appearance_time
    HV_0_0_29046: Errore attivo 5_appearance_time
    HV_50_0_0: Temperatura aria esterna
    HV_50_0_37600: "Umidit\xE0 aria ripresa"
    HV_50_0_37602: Temperatura aria ripresa
    HV_50_0_37608: VOC aria ripresa
    HV_50_0_37611: VOC aria esterna
    HV_50_0_38600: Ventilatore aria espulsa nominale
    HV_50_0_38606: Modulazione ventilazione
    HV_50_0_39600: "Regolazione qualit\xE0 dell'aria"
    HV_50_0_39652: Stato regolazione ventilazione
    HV_50_0_40650: Selezione modo funzion.to ventilazione
    HV_50_0_40651: Modulazione ventilazione normale
    HV_50_0_40686: Modulazione ventilazione risparmio
    HV_50_0_40687: "Valore nominale umidit\xE0"
