substitutions:
    HV_0_0_29042: Errore attivo 1_appearance_time
    HV_0_0_29043: Errore attivo 2_appearance_time
    HV_0_0_29044: Errore attivo 3_appearance_time
    HV_0_0_29045: Errore attivo 4_appearance_time
    HV_0_0_29046: Errore attivo 5_appearance_time
    HV_50_0_0: Temperatura aria esterna
    HV_50_0_37600: "Umidit\xE0 aria ripresa"
    HV_50_0_37602: Temperatura aria ripresa
    HV_50_0_37608: VOC aria ripresa
    HV_50_0_37611: VOC aria esterna
    HV_50_0_38600: Ventilatore aria espulsa nominale
    HV_50_0_38606: Modulazione ventilazione
    HV_50_0_39600: "Regolazione qualit\xE0 dell'aria"
    HV_50_0_39652: Stato regolazione ventilazione
    HV_50_0_40650: Selezione modo funzion.to ventilazione
    HV_50_0_40651: Modulazione ventilazione normale
    HV_50_0_40686: Modulazione ventilazione risparmio
    HV_50_0_40687: "Valore nominale umidit\xE0"
    
    HV_83_1_0: Photosensor
    HV_50_0_2010: Party mode timer [h]
    
    
    ##### values
    
    HV_50_0_39652_val_1: Modo ventilazione normale
    HV_50_0_39652_val_2: Modo VOC attivo
    HV_50_0_39652_val_3: "Modo umidit\xE0 attivo"
    HV_50_0_39652_val_4: Protezione antigelo attiva
    HV_50_0_39652_val_5: CoolVent attivo
    HV_50_0_39652_val_6: Stato errore
    HV_50_0_39652_val_7: Summer humidity
    HV_50_0_39652_val_8: Switch-off stop
    
    HV_50_0_40650_val_1 : Standby
    HV_50_0_40650_val_2 : Settimana 1
    HV_50_0_40650_val_3 : Settimana 2
    HV_50_0_40650_val_4 : Costante
    HV_50_0_40650_val_5 : Eco
