toptronic:
    id: tt

# Row: 3536
sensor:
  - platform: toptronic
    name: Raum-Ist
    device_type: 0
    device_addr: 0
    function_group: 1
    function_number: 0
    datapoint: 1
    type: S16
    unit_of_measurement: "\xB0C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
