toptronic:
    id: tt

sensor:
  - platform: toptronic
    name: Normal-Raumtemperatur Heizbetrieb
    device_type: 0
    device_addr: 0
    function_group: 1
    function_number: 0
    datapoint: 3051
    type: S16
    unit_of_measurement: "\xB0C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: toptronic
    name: Aussenfühler 1
    device_type: 0
    device_addr: 0
    function_group: 0
    function_number: 0
    datapoint: 0
    type: S16
    unit_of_measurement: "\xB0C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

# Row: 3510
number:
  - platform: toptronic
    name: Normal-Raumtemperatur Heizbetrieb
    device_type: 0 # ???
    device_addr: 0
    function_group: 1
    function_number: 0
    datapoint: 3051
    type: S16
    # unit_of_measurement: "\xB0C"
    min_value: 100
    max_value: 300
    step: 5

# Row: 1379
text_sensor:
  - platform: toptronic
    name: Betriebswahl Heizung
    device_type: 0
    device_addr: 0
    function_group: 1
    function_number: 0
    datapoint: 3050
    options:
      - Standby
      - Woche 1
      - Woche 2
      - Konstant
      - Sparbetrieb
      - Handbetrieb
    values:
      - 0
      - 1
      - 2
      - 4
      - 5
      - 7

select:
  - platform: toptronic
    name: Betriebswahl Heizung Select
    device_type: 0
    device_addr: 0
    function_group: 1
    function_number: 0
    datapoint: 3050
    options:
      - Standby
      - Woche 1
      - Woche 2
      - Konstant
      - Sparbetrieb
      - Handbetrieb
    values:
      - 0
      - 1
      - 2
      - 4
      - 5
      - 7
